channels:
- conda-forge
dependencies:
- python=3.8.19
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - gmpy2==2.1.2
  - jinja2==3.1.4
  - numpy==1.24.3
  - packaging==24.1
  - pandas==2.0.3
  - pyyaml==6.0.1
  - scipy==1.10.1
  - torch-geometric==2.5.2
  - torch==2.2.2
name: mlflow-env
